### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by Lordpluha** [Lordpluha/GameBlog#1]
@kowkaLYT Накидай 3-5 дизайнов или референсов для дизайна

**Comment by kowkaLYT** [comment]
**References:**
- https://www.theblondeabroad.com
- https://theeverygirl.com/#

**Templates:**
- https://www.figma.com/file/tBiy2a3InJyJTEAjJYe7WO/Grammy-Responsive-Personal-Blog-%26-Online-Newspaper?type=design&node-id=59-717&mode=design&t=m5Y7qgvA0ZABpbXT-0
- https://www.figma.com/file/rfMbitY40PuHpLMawDxdDV/WASTE-PROCESSING-BY-BEEMA---IL-(Community)?type=design&node-id=0-1&mode=design&t=zSDQr8m4j3KDrmUI-0
- https://www.figma.com/file/EzKcIjTsTFEAFH9o1ovdsC/Podcast-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&mode=design&t=v4l0n5DQFw6YmVgK-0
- https://www.figma.com/file/hL76iA2SDq9O4rrzSW2DtM/Cooking-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&mode=design&t=HWAktr5Ruw4S0Y6w-0

**Comment by kowkaLYT** [comment]
References:


- https://www.theblondeabroad.com/

- https://theeverygirl.com/#

Templates:

- https://www.figma.com/file/tBiy2a3InJyJTEAjJYe7WO/Grammy-Responsive-Personal-Blog-%26-Online-Newspaper?type=design&node-id=59-717&mode=design&t=m5Y7qgvA0ZABpbXT-0

- https://www.figma.com/file/rfMbitY40PuHpLMawDxdDV/WASTE-PROCESSING-BY-BEEMA---IL-(Community)?type=design&node-id=0-1&mode=design&t=zSDQr8m4j3KDrmUI-0

- https://www.figma.com/file/EzKcIjTsTFEAFH9o1ovdsC/Podcast-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&mode=design&t=v4l0n5DQFw6YmVgK-0

- https://www.figma.com/file/hL76iA2SDq9O4rrzSW2DtM/Cooking-Template-%F0%9F%9F%A3-by-Flowbase.co-(Community)?type=design&node-id=1-296&mode=design&t=HWAktr5Ruw4S0Y6w-0

**Comment by Lordpluha** [comment]
- **https://stopgame.ru/news**
- https://www.playground.ru/news
