### ISSUE TITLE
Adobt header component for flexebility

### ISSUE THREAD

**Issue by Lordpluha** [Lordpluha/GameBlog#51]
# Todolist:
- [x] max-width: 1146 - burger menu
- [x] fix flexebility of component elements
![image](https://github.com/Lordpluha/GameBlog/assets/109725756/73f71a7a-de03-4c35-b8af-7764e3c73438)

## Example of 1145px width original
![image](https://github.com/Lordpluha/GameBlog/assets/109725756/5ec3d22c-be2b-4ebb-88c9-3760d2b019a1)

**Comment by kiberchainik** [comment]
issue solved chief

**Comment by Lordpluha** [comment]
@kiberchainik add branch/pull request
